### ISSUE TITLE
Problem with latest commit changes in system tray

### ISSUE THREAD

**Issue by stefanos82** [lwindolf/liferea#1311]
![image](https://github.com/lwindolf/liferea/assets/1777466/cda71faa-0253-43ce-b2b7-b8ff767c9f1b)

If I'm not mistaken, I used to get a number of RSS feed that got updated; now I get this plain `unread.png` image without any red number in it.

Am I hallucinating? :confused:

**Comment by lwindolf** [comment]
@nE0sIghT do you have an idea what could cause the effect?

**Comment by nE0sIghT** [comment]
@stefanos82 
What Desktop engine do you use (GNOME, KDE, XFCE or some other)?

**Comment by stefanos82** [comment]
I use XFCE 4.18 if it helps @nE0sIghT

**Comment by sunwire** [comment]
Fedora 38 MATE Desktop (X11)
Tray icon doesn't respond on left click, right click works.
I have  a number of RSS feed, but it look strange and it disappears when I click next unread
 item.
![icon](https://github.com/lwindolf/liferea/assets/50745572/6fd7c822-b934-4b3f-91f2-0f94acc9862a)

**Comment by nE0sIghT** [comment]
There are 2 issues here.  
1. As I expected for XFCE (and other desktops without StatusNotifier support) we can use GTK.StatusIcon as before. I will create MR with the fix.
2. In case of Mate it looks like the bug in the Mate. I created issue [1] in the mate-desktop project for it. It looks like we can work-around this issue by changing normal icon to attention icon. I will test this workaround and create MR for it.

As a fix for mentioned here (and possible future) issues we can split of appindicator implementation from trayicon plugin to separate plugin. But code will be duplicated between plugins.

[1] https://github.com/mate-desktop/mate-desktop/issues/589

**Comment by sunwire** [comment]
@nE0sIghT I've tested https://github.com/lwindolf/liferea/pull/1312 and good news it looks ok
![icon](https://github.com/lwindolf/liferea/assets/50745572/a88d6847-8a05-4e4a-b86d-025eb1f58e88)
Bad news, still left click on the icon does not open the liferea window

**Comment by nE0sIghT** [comment]
@sunwire 
I pushed new commit to MR that adds secondary activation action to icon.  
In GNOME is is middle mouse click.  
As I see AppIndicator doesn't allows to set left/right mouse click actions (this is same for eg Telegram, Element, Firewalld etc)

**Comment by sunwire** [comment]
> I pushed new commit to MR that adds secondary activation action to icon.
> In GNOME it is middle mouse click.

Thanks for quick response, in MATE Desktop works the same.

**Comment by nE0sIghT** [comment]
> Thanks for the quick reply, in MATE Desktop works the same

Just checked Fedora 38 with Mate - works fine here. Middle mouse click toggles Liferea window display.

**Comment by stefanos82** [comment]
Excuse me but, I was the one who opened the ticket and wasn't even asked whether the issue was fixed on my side or not; clearly, I still face the same issue with the latest commit

![image](https://github.com/lwindolf/liferea/assets/1777466/79a209db-57d8-4e33-9a04-a1b90f0a0dc0)

Can we please re-open the issue until it's being resolved on all platforms?

**Comment by lwindolf** [comment]
@stefanos82 Your initial report was already impolite and your comment above is even more out of place. Have a look at the commit and you will find this was a Github auto close done by no-one.

Overall I understand that the new solution does not cover your use case which is bad for you. Still I consider going with it because I have to support the entire user base in a good way and the new solution improves a lot. As a maintainer I have to judge on the trade-offs and will **NOT** keep this issue open until fixed on all platforms. I will keep this issue open as long as it helps me in maintaining the project for all users.

You might well disagree with the choice, in this case feel free to fork the project and do better.

**Comment by stefanos82** [comment]
> Your initial report was already impolite and your comment above is even more out of place. Have a look at the commit and you will find this was a Github auto close done by no-one.

...so asking **myself** whether or not **I'm personally hallucinating** for not viewing a red number in system tray is considered impolite by you?

I honestly don't know what to say.

Keep up the good work and stay curious :+1: 

Good luck.

**Comment by nE0sIghT** [comment]
@stefanos82 
I checked changes on XFCE (Ubuntu 23.10) and it works as before - AppIndicator is not used if StatusNotifier is missing. So you should get previous behavior with red counter.

**Comment by stefanos82** [comment]
> @stefanos82 I checked changes on XFCE (Ubuntu 23.10) and it works as before - AppIndicator is not used if StatusNotifier is missing. So you should get previous behavior with red counter.

The issue remains the same as above

![image](https://github.com/lwindolf/liferea/assets/1777466/9dbd7726-da72-4947-a15a-2d371cb0606a)

Is there anything I should check to help you with further debugging?

**Comment by nE0sIghT** [comment]
I was wrong - XFCE do expose StatusNotifier DBus interface. However it looks incomplete since it doesn't show attention label.  
Try to report this to https://gitlab.xfce.org/xfce/xfce4-panel/-/issues

**Comment by raveit65** [comment]
@sunwire 
There is a scratch build for f38 with a fix from MATE upstream, please test.
https://koji.fedoraproject.org/koji/taskinfo?taskID=108144692
