### ISSUE TITLE
Missing js directory when building from tarballs

### ISSUE THREAD

**Issue by Lucidiot** [lwindolf/liferea#1408]
## Version

1.15.9

## Problematic Behavior

I am trying to update the [Alpine Linux package](https://github.com/lwindolf/liferea) for Liferea, which downloads the source for the current version through the `.tar.bz2` archive attached on each release. But when trying to build from either the `.tar.bz2` or the source archives provided by GitHub, I get this error:

```
Making all in .
make[3]: Entering directory '/home/lucidiot/aports/community/liferea/src/liferea-1.15.9/src'
make[3]: *** No rule to make target '../js/gresource.xml', needed by 'js.c'.  Stop.
```

## Steps to Reproduce

1. Download and extract any of the assets from [the 1.15.9 release](https://github.com/lwindolf/liferea/releases/tag/v1.15.9)
2. Run `./configure`
3. Run `make`

## Expected Behavior

It should build!

This does not occur when building using a Git clone (something that I shouldn't do in an Alpine package). I think this is caused by [this line](https://github.com/lwindolf/liferea/blob/4be3c6a8da3efadd6bc771e58b8c92eb662f5e11/.gitignore#L44) in the `.gitignore`, which excludes the `gresource.xml` file even though it is still present in the repo.

**Comment by lwindolf** [comment]
Thank you for the report. I fixed the .gitignore and the files missing declaration as EXTRA_DIST. I've ran a `make distcheck` to ensure it works. Sorry about forgetting to do so when releasing.

A new release tarball liferea-1.15.9b.tar.bz2 has been added to the release.

**Comment by sunwire** [comment]
> A new release tarball liferea-1.15.9b.tar.bz2 has been added to the release.

The new release fails to compile!
https://github.com/lwindolf/liferea/actions/runs/12967500195/job/36169433100#step:7:265

**Comment by lwindolf** [comment]
@sunwire Saw this too. Didn't expect this. I ran a `make distcheck` on my local Ubuntu 24.10. Confusing...

**Comment by sunwire** [comment]
> Confusing...

I compiled version 1.15.9b on Fedora 41 and I have the same errors.

The previous version 1.15.9, although it compiled correctly on Fedora, also had errors, and the preview did not work at all.
I didn't report it because I was trying to find out what happened first.
```
CPPFLAGS="" CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -march=haswell -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --std=c99 -D_DEFAULT_SOURCE" LDFLAGS="-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes " CC="gcc" PKG_CONFIG="/usr/bin/pkg-config" GI_HOST_OS="" DLLTOOL="false"  /usr/bin/g-ir-scanner  -I../src --warn-all --accept-unprefixed --identifier-prefix=Liferea --verbose --namespace=Liferea --nsversion=3.0 --libtool="/bin/sh ../libtool"  --include=Gtk-3.0 --include=libxml2-2.0   --program=./liferea   --cflags-begin  --cflags-end  auth.c auth.h download.c download.h enclosure.h feedlist.c feedlist.h item.h itemlist.c itemlist.h itemset.c itemset.h liferea_application.h net_monitor.h net_monitor.c node.h node.c node_provider.c node_provider.h node_source.c node_source.h node_view.h social.c social.h subscription_type.h update.h update_job.h update_job_queue.h ui/browser_tabs.c ui/browser_tabs.h ui/icons.c ui/icons.h ui/itemview.c ui/itemview.h ui/item_list_view.c ui/item_list_view.h ui/liferea_browser.c ui/liferea_browser.h ui/liferea_shell.c ui/liferea_shell.h plugins/auth_activatable.c plugins/auth_activatable.h plugins/download_activatable.c plugins/download_activatable.h plugins/liferea_shell_activatable.c plugins/liferea_shell_activatable.h plugins/node_source_activatable.c plugins/node_source_activatable.h liferea --output Liferea-3.0.gir
download.c:2: Error: Liferea: identifier not found on the first line:
 * @file download.h  Managing downloads
   ^
node_provider.c:2: Error: Liferea: identifier not found on the first line:
 * node_provider.c:  node provider handling
   ^
ui/liferea_browser.c:469: Error: Liferea: Skipping invalid GTK-Doc comment block:
/** render parameter type */
^
download.h:2: Error: Liferea: identifier not found on the first line:
 * @file download.h  Managing downloads
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
update.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_request.h  generic update request processing
   ^
update_job.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_job.h  handling update processing (network/local/filter/XSLT)
   ^
update_job.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_job.h  handling update processing (network/local/filter/XSLT)
   ^
update.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_request.h  generic update request processing
   ^
update_job_queue.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_job_queue.h  handling async concurrent update processing
   ^
update.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_request.h  generic update request processing
   ^
update_job.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_job.h  handling update processing (network/local/filter/XSLT)
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
node_provider.h:2: Error: Liferea: identifier not found on the first line:
 * node_provider.h:  node provider handling
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
node_provider.h:2: Error: Liferea: identifier not found on the first line:
 * node_provider.h:  node provider handling
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
update.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_request.h  generic update request processing
   ^
update.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_request.h  generic update request processing
   ^
update_job.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_job.h  handling update processing (network/local/filter/XSLT)
   ^
update_job_queue.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_job_queue.h  handling async concurrent update processing
   ^
update.h:2: Error: Liferea: identifier not found on the first line:
 * @file update_request.h  generic update request processing
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
node.h:2: Error: Liferea: identifier not found on the first line:
 * @file node.h  hierarchic feed list node interface
   ^
update_job.h:57: Warning: Liferea: update_job_new: argument callback: Missing (scope) annotation for callback without GDestroyNotify (valid: call, async, forever)
```

**Comment by lwindolf** [comment]
I can now reproduce the effect.

**Comment by lwindolf** [comment]
Fixed with 718f7125

I've replaced the release tarball with a new liferea-1.15.9c.tar.bz2

**Comment by Lucidiot** [comment]
[The upgrade](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/79035) went through, thanks!

**Comment by cofi89** [comment]
> > Confusing...
> 
> I compiled version 1.15.9b on Fedora 41 and I have the same errors.
> 
> The previous version 1.15.9, although it compiled correctly on Fedora, also had errors, and the preview did not work at all. I didn't report it because I was trying to find out what happened first.
> 
> ```
> CPPFLAGS="" CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -march=haswell -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --std=c99 -D_DEFAULT_SOURCE" LDFLAGS="-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes " CC="gcc" PKG_CONFIG="/usr/bin/pkg-config" GI_HOST_OS="" DLLTOOL="false"  /usr/bin/g-ir-scanner  -I../src --warn-all --accept-unprefixed --identifier-prefix=Liferea --verbose --namespace=Liferea --nsversion=3.0 --libtool="/bin/sh ../libtool"  --include=Gtk-3.0 --include=libxml2-2.0   --program=./liferea   --cflags-begin  --cflags-end  auth.c auth.h download.c download.h enclosure.h feedlist.c feedlist.h item.h itemlist.c itemlist.h itemset.c itemset.h liferea_application.h net_monitor.h net_monitor.c node.h node.c node_provider.c node_provider.h node_source.c node_source.h node_view.h social.c social.h subscription_type.h update.h update_job.h update_job_queue.h ui/browser_tabs.c ui/browser_tabs.h ui/icons.c ui/icons.h ui/itemview.c ui/itemview.h ui/item_list_view.c ui/item_list_view.h ui/liferea_browser.c ui/liferea_browser.h ui/liferea_shell.c ui/liferea_shell.h plugins/auth_activatable.c plugins/auth_activatable.h plugins/download_activatable.c plugins/download_activatable.h plugins/liferea_shell_activatable.c plugins/liferea_shell_activatable.h plugins/node_source_activatable.c plugins/node_source_activatable.h liferea --output Liferea-3.0.gir
> download.c:2: Error: Liferea: identifier not found on the first line:
>  * @file download.h  Managing downloads
>    ^
> node_provider.c:2: Error: Liferea: identifier not found on the first line:
>  * node_provider.c:  node provider handling
>    ^
> -- SNIP --
> update_job.h:57: Warning: Liferea: update_job_new: argument callback: Missing (scope) annotation for callback without GDestroyNotify (valid: call, async, forever)
> ```

I'm getting the same error(s) as [above](https://github.com/lwindolf/liferea/issues/1408#issuecomment-2614213069), with both 1.15.9c && 1.16-RC1 on Debian Bookworm, and with the same result  of preview not working (it's completely blank).  
They're also still present in the latest CI build (as of writing):  
https://github.com/lwindolf/liferea/actions/runs/13348654910/job/37282327648#step:7:238

**Comment by lwindolf** [comment]
@cofi89 The gir-scanner errors that you mention are 100% harmless. The cannot have any effect on the HTML rendering.

I consider the missing files to be fixed in 1.15.9c and 1.16-RC1. 

If you still have problem please provide the CLI output of a "make install". Please open a new issue for this
