### ISSUE TITLE
Removing an item from search folder "Unread" marks all (unread) items as read

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#180]
Removing an item from search folder "Unread" marks all unread items (or all items) as read.

* Select search folder "Unread".
* Select an item.
* Remove an item using item context menu (right-click).

Using
Liferea 1.11.4
Salix OS 14.1

**Comment by lwindolf** [comment]
Reproduced

**Comment by lwindolf** [comment]
Affects 1.10 also. Fixed in both 1.10 branch and master.

**Comment by GreenLunar** [comment]
Perhaps user should not be able to remove items from a Search Folder.

**Comment by GreenLunar** [comment]
It occurs also when on view of items from several feeds (by selecting a folder) are listed.

**Comment by Mno-hime** [comment]
I think the problem is not fixed. About once a month all items in my "Unread" search folder are marked as read and

```
Gtk-CRITICAL **: gtk_tree_store_get_path: assertion 'iter->stamp == priv->stamp' failed
```

line per item marked as read is to be found in journalctl log. I was always suspecting http://blisty.cz/rss2.rb?all=1 feed since they tend to add and remove items to/from the feed as they are pleased. I added the one-liner patch

```
        if (item) {
+               itemview_select_item (NULL);
                itemlist_remove_item (item);
```

which was supposed to fix the problem to my Fedora 1.10.15 version of liferea and now I was hit by the bug (now I am building 1.10.16). Or is it another bug?
