### ISSUE TITLE
building fails on f25 with introspection

### ISSUE THREAD

**Issue by bitlord** [lwindolf/liferea#398]
I have latest git revision build and run on my fedora 24 box and on my gentoo box, but I tried to build and run liferea on f25, and I'm having issues building it, as a workaround I set 
`--enable-introspection=no`

I'll attach the problematic part of the build log.
[liferea_f25_build.txt](https://github.com/lwindolf/liferea/files/499276/liferea_f25_build.txt)

I'm sorry if this is not a bug, but just lack of knowledge on my side on how to build things from source.

**Comment by paulgevers** [comment]
I was encounting the same issue in my Debian build environment, but NOT in my normal environment. I suspected that a live X session was needed. Do you also build in a clean environment?

I filed Debian bug 839397¹ against webkit2 about this.

¹ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839397

**Comment by bitlord** [comment]
@paulgevers yes I was using mock with different user(s) from one running X session to build the package, but on f24 where it was building fine I also used mock, on gentoo box I was building it manually.

**Comment by paulgevers** [comment]
@bitlord: I failed to notice the first time that you successfully build
on an older version of Fedora. I have the same issue in Debian: Debian
stable is OK, while Debian sid (unstable) isn't. On Debian stretch
(testing) it succeeded with the working X session. Not sure what to make
of it, but it looks to me that this is NOT liferea, but something in the
stack that needs fixing. My Debian bug report is against webkit2, but it
may also be in gobject-introspection or even elsewhere. I guess we need
to figure out which version of which package broke building liferea.
I'll think about how to bisect this, but if anybody has a good idea,
please shim in.

Paul

**Comment by paulgevers** [comment]
@bitlord: today I bisected this for as far as I can in Debian. It really seems to be re2.13.4-1+b2 succeeded, while with 2.13.91-1lated to webkit2gtk and its latest versions. The latest version that was OK in Debian was 2.13.4-1, while 2.13.91 shows the problematic behavior. I updated the Debian bug with that info, let's hope that the Debian webkit2gtk maintainers have more insight in this. You could also take this upstream, as you experience it in Fedora, while I see it in Debian.

Which versions of webkit2gtk do you have, both working and no-working?

**Comment by paulgevers** [comment]
I received a work-around in the Debian bug report against webkit2gtk. Export the environment variable WEBKIT_DISABLE_COMPOSITING_MODE=1 before you build liferea and it should work (it does for me).

**Comment by bitlord** [comment]
First, I'm sorry for being late to respond to this.
Second, thank you @paulgevers  for the solution, works for me also by exporting WEBKIT_DISABLE_COMPOSITING_MODE=1 in build environment.

All this testing is done before with pre-release of webkitgtk 2.14 (2.13.xx), and now with webkitgtk-2.14.1.

**Comment by paulgevers** [comment]
Fixed upstream: https://bugs.webkit.org/show_bug.cgi?id=163105

Not sure if they agree with our work around, so we probably should remove it once the fix is in our distribution of choice.

**Comment by paulgevers** [comment]
I think this bug can be closed as "not a bug in Liferea".

**Comment by bitlord** [comment]
@paulgevers 
I agree, I'm not sure how can I put the status, but closing it is enough.

Thanks for your help!

**Comment by da2x** [comment]
This is still an issue with the current master and Fedora 27 w/Wayland.

**Comment by zaitcev** [comment]
F27 has webkitgtk4-devel-2.18.3-1.fc27.x86_64, maybe the fix is not there yet?

**Comment by paulgevers** [comment]
@zaitcev the Debian changelog says the issue in webkitgtk4 was solved in 2.14.2, so either this is a regression, or the issue is different in fedora. In Debian, I haven't seen this issue anymore.

**Comment by bitlord** [comment]
@zaitcev it seems that is another webkitgtk[1] issue reported also as #552 in liferea.
Since it was commited three weeks ago, it probably only went into webkitgtk 2.20.x
[1] https://bugs.webkit.org/show_bug.cgi?id=176490
